### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by mommyme** [gmarm/BetterSegmentedControl#14]
Is there a way that this control will be used with images, and different selected images? That would be amazing.

**Comment by gmarm** [comment]
Have a look at this: https://github.com/gmarm/BetterSegmentedControl/issues/7

Short answer, not yet.

**Comment by mommyme** [comment]
Great. Thank you again for this control. It is fantastic. Looking forward to the images.

**Comment by mommyme** [comment]
@gmarm I hate to be a bother, but I am trying to put out an update to an app ASAP. I would like to use this control but I don't know swift. Do you have any idea of your timeline for including images (i.e. a week, a month, a year)? Any info at all would be extremely helpful. Thanks.

**Comment by gmarm** [comment]
I work on the control when I find the time since I work full time and this is simply a side project.

Images should come in the next months but I can't be more precise here.

 I would suggest the following: 
1. Have a look at [NYSegmentedControl](https://github.com/nealyoung/NYSegmentedControl). I remember I was able to subclass it a few years back and support image segments without too much effort.
2. Use BetterSegmentedControl with Emoji. Emoji rocks.

**Comment by mommyme** [comment]
Oh, I didn't realize I could use it with emoji! I will have to figure out how to do that. And thanks again for all that you do with this! I understand it is a side project. It is very much appreciated : )
Jen

**Comment by mommyme** [comment]
The emojis do not work well for me but I absolutely love this control. Is there any way to use the control with ligatures? Ligatures with icon fonts would be a great way to get images into the control if this were possible.

**Comment by mommyme** [comment]
You don't have a copy of the NYSegmentedControl subclass do you? I am having a hard time trying to subclass it effectively. Can't wait until this control has images : ) I would pay for this with images!!!
