### ISSUE TITLE
IBDesignables don't render, complains about tvOS (no tvOS target)

### ISSUE THREAD

**Issue by AccuPhoenix01** [gmarm/BetterSegmentedControl#148]
Just imported BSC via Swift Package and trying in my project. Works fine via code, but most of the IBDesignable items won't render on my layout. CornerRadius works. XCode complains that SystemBackground, UIPointerRegion, UIPointerStyle are not available on tvOS. My project does NOT use tvOS in any way, there is no tvOS target. I have a basic iOS app with a widget, iOS 14 widget, widget intent file, and watch OS app/extension.

I have not tried to import via Cocoapods but will try to see if errors go away. UPDATE: _Works OK via Cocoapods_!

Using XCode 12.2 (12B45b)

![image](https://user-images.githubusercontent.com/46455562/100151427-20b65580-2e6f-11eb-89e0-fbcd31ca410b.png)

~~Side question - how do I get the storyboard to display items "first second third"? Or will this ^ fix it?~~ yes it does

**Comment by gmarm** [comment]
Hmm, not sure what the issue could be with integration via SPM. Perhaps something in Build Settings?

In a test project I tested it with it worked fine, and in `Package.swift`, only iOS platform is defined.

```
...
platforms: [
        .iOS(.v9),
    ],
...
```

Glad that integration as a pod fixes the issue though.

**Comment by michaelschwinges** [comment]
I am also running into this issue, and I came across the following on SO:

https://stackoverflow.com/questions/64037687/very-strange-errors-from-ib-during-build-with-swift-package-using-ibdesignable/66334661#66334661

Essentially, according to the Apple docs quoted, the 'platforms' parameter in Package.swift does not define where the package is available, it defines the minimum required version for the given platform.

It will try to build for all platforms unless you wrap the offending code within #if os(iOS) etc.

Edit: not sure switching from CocoaPods to SPM is the ideal solution, since as much-loved as CocoaPods is, not sure it's where things are headed?
