### ISSUE TITLE
Duplicate schemes

### ISSUE THREAD

**Issue by gmarm** [gmarm/BetterSegmentedControl#34]
https://github.com/gmarm/BetterSegmentedControl/pull/33 and https://github.com/gmarm/BetterSegmentedControl/pull/30 both edited the shared schemes, however now the schemes look like this:

![screen shot 2016-10-03 at 13 33 20](https://cloud.githubusercontent.com/assets/1718656/19036157/4e1bf3c2-896e-11e6-87fa-0d2c71f6db28.png)

Is this how it should be for Carthage to work? Can we do away with the duplication? @calvingit, @LukeDurrant ?

**Comment by calvingit** [comment]
You should see the "Manage Schemes", like below screenshot on master branch:
![qq20161003-0](https://cloud.githubusercontent.com/assets/2109371/19040749/fcfd1d00-89b7-11e6-8c77-a5817916c2e2.png)

Carthage will only search the Framework project to build . So it doesn't matter if there are two shared schemes, because Carthage would not build the BetterSegmentedControl-Example project.

**Comment by gmarm** [comment]
Hmm seems there was some conflict with my local repo. Recloning the repo seems to fix it. Closing this.
