### ISSUE TITLE
Shy segmented control 

### ISSUE THREAD

**Issue by bkvirendra** [gmarm/BetterSegmentedControl#53]
I have the segmented control just below the navigation bar and would like to hide it when the user scrolls the page down and display it with when the user scrolls above. This is just like the shy navigation bar feature.

**Comment by gmarm** [comment]
hey @bkvirendra , when you say below do you mean it's in the view _under_ the navigation or is it added as a subview _to_ the navigation bar?

**Comment by bkvirendra** [comment]
It's located just under the navigation bar, as seen in the screenshot below.

The navigation bar exists in the standard size.

![screenshot 2017-05-24 16 55 30](https://cloud.githubusercontent.com/assets/1097043/26412798/d2cdc1e6-40a1-11e7-9d8f-ab10d718f5e9.png)

**Comment by gmarm** [comment]
Alright then I don't think this has anything to do with the control itself, it behaves like any `UIView` really since it's a direct subclass.

What I would suggest is creating an outlet for the control, and then using it inside the `scrollViewDidScroll` delegate method of your `UIScrollView` / `UITableView` to show and hide the control using its `alpha` property.
